# alembic configuration file

[alembic]
# path to migration scripts (relative to this file)
script_location = alembic

# template used to generate migration file names
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(slug)s

# set to 'true' to run the environment during the generation
prepend_sys_path = .

# timezone for the revision timestamps
timezone = UTC

# version path separator for output_encoding
version_path_separator = os

# the output encoding used when revision files are written (python 3)
output_encoding = utf-8

# sqlalchemy url - overridden by env.py using app settings
sqlalchemy.url = driver://user:pass@localhost/dbname


[post_write_hooks]
# post write hooks to run after a revision is generated

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
